# Generated by Django 3.0.4 on 2020-05-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
                ('domain', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date added')),
                ('linked', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('aggregator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('aggregator', models.CharField(max_length=200)),
            ],
        ),
    ]
