# Generated by Django 3.0.4 on 2020-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='htpp://www.example.com', max_length=2000)),
                ('title', models.CharField(default='Example', max_length=2000)),
                ('summary', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('domain', models.CharField(blank=True, default='example.com', max_length=2000, null=True)),
                ('added', models.DateTimeField(default='1900-01-01', verbose_name='date added')),
                ('modified', models.DateTimeField(default='1900-01-01', verbose_name='date modified')),
                ('liked', models.IntegerField(blank=True, default=1, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('aggregator', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
