# Generated by Django 3.0.4 on 2020-06-06 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='date modified'),
        ),
    ]
