# Generated by Django 3.0.4 on 2020-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20200606_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='benched',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
