# Generated by Django 3.1.6 on 2021-03-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_link_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(default='http://www.example.com', max_length=2000),
        ),
    ]
