# Generated by Django 3.0.4 on 2020-05-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20200517_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='aggregator',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='summary',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='aggregator',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
