# Generated by Django 3.0.4 on 2020-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20200517_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
