# Generated by Django 3.0.4 on 2020-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20200524_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
