# Generated by Django 3.1.6 on 2021-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20210716_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tweet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
