# Generated by Django 3.0.4 on 2020-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_auto_20200524_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upcoming',
        ),
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='liked',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
