# Generated by Django 3.1.6 on 2021-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_auto_20210716_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='liked',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='seed',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='tweet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
