# Generated by Django 3.0.4 on 2020-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_auto_20200524_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='aggregator',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
