# Generated by Django 3.0.4 on 2020-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_auto_20200524_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='aggregator',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.CharField(blank=True, default='example.com', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(default='Example', max_length=2000),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(default='htpp://www.example.com', max_length=2000),
        ),
    ]
