# Generated by Django 3.0.4 on 2020-05-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_auto_20200524_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='date',
        ),
        migrations.AddField(
            model_name='link',
            name='added',
            field=models.DateTimeField(default='1900-01-01', verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='link',
            name='modified',
            field=models.DateTimeField(default='1900-01-01', verbose_name='date modified'),
        ),
    ]
